### ISSUE TITLE
Bump json jar version to latest

### ISSUE THREAD

**Issue by KanakamedalaSiri** [jenkinsci/custom-markup-formatter-plugin#6]
There is High vulnerability reported with current dependency version of json-20230618.jar. Please bump json-20230618.jar to json-20240303.jar.

**Comment by KanakamedalaSiri** [comment]
@dhavalpateln Can you please help on updating vulnerable json dependency version to latest.

**Comment by jonesbusy** [comment]
This plugin should not bundle this jar directly but use https://plugins.jenkins.io/json-api/ as dependency

**Comment by MarkEWaite** [comment]
@KanakamedalaSiri you can use the incremental build of the plugin with the fix for this issue.  See the [incrementals check](https://github.com/jenkinsci/custom-markup-formatter-plugin/pull/7/checks?check_run_id=28120834915) for the details.

**Comment by MarkEWaite** [comment]
@KanakamedalaSiri will you share the results of your use of the incremental build of the plugin?

**Comment by KanakamedalaSiri** [comment]
> @KanakamedalaSiri will you share the results of your use of the incremental build of the plugin?

Tested incremental build with our current Jenkins version of 2.462.1. All good in our case with description drop downs.
![image](https://github.com/user-attachments/assets/ec304f34-32cd-4c42-a71d-9d1809b65a6e)
Previously few attributes like Div id and class are got removed which caused the dropdowns  no longer work, now they are good with custom policy.

**Comment by KanakamedalaSiri** [comment]
This was good, when can this be released?

> @KanakamedalaSiri you can use the incremental build of the plugin with the fix for this issue. See the [incrementals check](https://github.com/jenkinsci/custom-markup-formatter-plugin/pull/7/checks?check_run_id=28120834915) for the details.

This was Good. When can this be released?

**Comment by MarkEWaite** [comment]
> This was good, when can this be released?

Since it has been 4 weeks since you reported your tests were successful, I think that your next step may be to request to be added as one of the maintainers of the plugin so that you can merge and release the change.  Follow the ["adopt a plugin"](https://www.jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/) instructions.

Since the plugin has automated release enabled, once you are approved as a maintainer, then all you need to do is add the "developer" or "enhancement" label to the pull request and merge it.  The release will then happen automatically.  The pull request is::

* #7
